/**
 * BookScan — Mock Data
 * ====================
 * Realistic UK-flavoured data for the frontend mock mode.
 * All book descriptions are original summaries — no copyrighted text.
 * Numbers are internally consistent: stats totals equal the sums of
 * the sales and books arrays.
 */

import type {
  ActivityEntry,
  Book,
  Dataset,
  MonthlyRevenuePoint,
  PlatformRevenueSlice,
  RevenueSummary,
  Sale,
  StatsSummary,
  TriageDistributionSlice,
  TriageHistoryEntry,
  TriageResult,
} from './types';

// ── Helper ────────────────────────────────────────────────────────────────────

function uuid(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

// ── Books ─────────────────────────────────────────────────────────────────────

export const MOCK_BOOKS: Book[] = [
  {
    id: 'b1a2c3d4-0001-4000-8000-000000000001',
    isbn: '9781234567890',
    title: 'A Complete System of Botany for the Use of Students',
    subtitle: 'Comprising the Natural System and an Introduction to Classification',
    author_name: 'Dr Reginald Fortescue Hayward',
    author_birth_year: 1851,
    author_death_year: 1928,
    publisher: 'Chapman & Hall',
    publish_year: 1905,
    publish_date_exact: '1905-03-15',
    language: 'en',
    page_count: 614,
    genre: 'Natural History',
    subject_keywords: ['botany', 'taxonomy', 'flora', 'classification', 'natural history'],
    description:
      'A thorough systematic guide to botanical classification written for university students, covering the natural system from cryptogams to angiosperms with extensive illustrated keys.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1928, UK PD since 1998 (life + 70 years).',
    public_domain_checked_at: '2026-01-10T09:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: 'OL123456M',
    openlibrary_url: 'https://openlibrary.org/books/OL123456M',
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'rare',
    worldcat_holding_count: 12,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: botany',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: 'High-value niche domain. No Gutenberg copy found.',
    triage_score: 95,
    triage_run_at: '2026-01-10T09:05:00Z',
    physical_location: 'Shelf A1',
    acquisition_cost: 3.5,
    acquisition_date: '2025-12-01',
    acquisition_source: 'Oxfam Bookshop, Cambridge',
    condition: 'very_good',
    scan_status: 'ready_for_sale',
    scan_method: 'document_scanner',
    scan_started_at: '2026-01-12T10:00:00Z',
    scan_completed_at: '2026-01-14T16:30:00Z',
    ocr_text_path: '/ocr-text/b1a2c3d4-0001.txt',
    ocr_quality_score: 0.94,
    ocr_word_count: 187_420,
    ocr_page_count: 614,
    resale_status: 'listed',
    resale_platform: 'abebooks',
    resale_price: 22.0,
    resale_listed_at: '2026-01-15T08:00:00Z',
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2025-12-01', detail: 'Oxfam Bookshop, Cambridge', cost: 3.5 },
      { event: 'Triage', date: '2026-01-10', detail: 'SCAN & SELL DATA — score 95' },
      { event: 'Scan', date: '2026-01-12', detail: 'Scanned with document scanner', method: 'document_scanner' },
      { event: 'Listed for resale', date: '2026-01-15', detail: 'AbeBooks', platform: 'abebooks', price: 22.0 },
    ],
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'b1a2c3d4-0002-4000-8000-000000000002',
    isbn: '9780198012345',
    title: 'Practical Navigation and Nautical Astronomy',
    subtitle: null,
    author_name: 'Captain James Wentworth Pryce RN',
    author_birth_year: 1840,
    author_death_year: 1912,
    publisher: 'J. D. Potter',
    publish_year: 1888,
    publish_date_exact: null,
    language: 'en',
    page_count: 452,
    genre: 'Navigation',
    subject_keywords: ['navigation', 'astronomy', 'nautical', 'seamanship', 'spherical trigonometry'],
    description:
      'A definitive manual of celestial navigation and nautical astronomy for officers of the Royal Navy and merchant marine, with extensive tables of logarithms and worked examples.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1912, UK PD since 1982 (life + 70 years).',
    public_domain_checked_at: '2026-01-11T11:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'rare',
    worldcat_holding_count: 8,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: navigation, astronomy',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: 'Exceptionally rare. No digital copy found anywhere.',
    triage_score: 100,
    triage_run_at: '2026-01-11T11:10:00Z',
    physical_location: 'Shelf A2',
    acquisition_cost: 5.0,
    acquisition_date: '2026-01-05',
    acquisition_source: 'Hay-on-Wye, Richard Booth Books',
    condition: 'good',
    scan_status: 'ocr_complete',
    scan_method: 'dslr',
    scan_started_at: '2026-01-18T09:00:00Z',
    scan_completed_at: '2026-01-20T17:00:00Z',
    ocr_text_path: '/ocr-text/b1a2c3d4-0002.txt',
    ocr_quality_score: 0.89,
    ocr_word_count: 142_800,
    ocr_page_count: 452,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-01-05', detail: "Hay-on-Wye, Richard Booth Books", cost: 5.0 },
      { event: 'Triage', date: '2026-01-11', detail: 'SCAN & SELL DATA — score 100' },
      { event: 'Scan', date: '2026-01-18', detail: 'DSLR copy stand', method: 'dslr' },
    ],
    created_at: '2026-01-11T11:00:00Z',
    updated_at: '2026-01-20T17:00:00Z',
  },
  {
    id: 'b1a2c3d4-0003-4000-8000-000000000003',
    isbn: '9780123456789',
    title: 'The Principles of Organic Chemistry',
    subtitle: 'A Treatise for Advanced Students and Practitioners',
    author_name: 'Professor Archibald Soames Trent',
    author_birth_year: 1872,
    author_death_year: 1945,
    publisher: 'Longmans, Green and Co.',
    publish_year: 1921,
    publish_date_exact: null,
    language: 'en',
    page_count: 788,
    genre: 'Chemistry',
    subject_keywords: ['chemistry', 'organic chemistry', 'synthesis', 'reaction mechanisms'],
    description:
      'An advanced monograph on organic chemistry addressing reaction mechanisms, synthetic routes, and stereochemistry, intended for postgraduate students and industrial chemists.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1945, UK PD since 2015 (life + 70 years).',
    public_domain_checked_at: '2026-02-01T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: 'OL234567M',
    openlibrary_url: 'https://openlibrary.org/books/OL234567M',
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 31,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: chemistry',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 90,
    triage_run_at: '2026-02-01T10:10:00Z',
    physical_location: 'Shelf B1',
    acquisition_cost: 4.0,
    acquisition_date: '2026-01-22',
    acquisition_source: 'British Heart Foundation, Oxford',
    condition: 'good',
    scan_status: 'scanned',
    scan_method: 'document_scanner',
    scan_started_at: '2026-02-05T09:00:00Z',
    scan_completed_at: '2026-02-07T14:00:00Z',
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-01-22', detail: 'British Heart Foundation, Oxford', cost: 4.0 },
      { event: 'Triage', date: '2026-02-01', detail: 'SCAN & SELL DATA — score 90' },
    ],
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-07T14:00:00Z',
  },
  {
    id: 'b1a2c3d4-0004-4000-8000-000000000004',
    isbn: '9780000111223',
    title: 'Materia Medica and Therapeutics',
    subtitle: 'For Physicians and Students',
    author_name: 'Dr Edmund Calverley Hartley',
    author_birth_year: 1865,
    author_death_year: 1938,
    publisher: 'J. & A. Churchill',
    publish_year: 1914,
    publish_date_exact: null,
    language: 'en',
    page_count: 542,
    genre: 'Medicine',
    subject_keywords: ['medicine', 'pharmacology', 'therapeutics', 'drugs', 'clinical medicine'],
    description:
      'A comprehensive reference for physicians covering drug actions, dosages, contraindications, and therapeutic applications for conditions encountered in Edwardian clinical practice.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1938, UK PD since 2008 (life + 70 years).',
    public_domain_checked_at: '2026-02-10T09:30:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 24,
    ai_training_value: 'high',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: medicine',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 82,
    triage_run_at: '2026-02-10T09:40:00Z',
    physical_location: 'Shelf B2',
    acquisition_cost: 3.0,
    acquisition_date: '2026-02-08',
    acquisition_source: 'Age UK, Bristol',
    condition: 'good',
    scan_status: 'queued',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-02-08', detail: 'Age UK, Bristol', cost: 3.0 },
      { event: 'Triage', date: '2026-02-10', detail: 'SCAN & SELL DATA — score 82' },
    ],
    created_at: '2026-02-10T09:30:00Z',
    updated_at: '2026-02-10T09:40:00Z',
  },
  {
    id: 'b1a2c3d4-0005-4000-8000-000000000005',
    isbn: '9780000223344',
    title: 'Systematic Theology and the Philosophy of Religion',
    subtitle: null,
    author_name: 'Rev. Thomas Aldous Finbury DD',
    author_birth_year: 1848,
    author_death_year: 1920,
    publisher: 'T. & T. Clark',
    publish_year: 1899,
    publish_date_exact: null,
    language: 'en',
    page_count: 720,
    genre: 'Theology',
    subject_keywords: ['theology', 'philosophy', 'religion', 'systematic theology', 'metaphysics'],
    description:
      'A scholarly work examining the foundations of Christian doctrine through the lens of late-Victorian philosophical idealism, engaging with Hegel, Kant, and contemporary British theologians.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1920, UK PD since 1990 (life + 70 years).',
    public_domain_checked_at: '2026-02-15T14:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'rare',
    worldcat_holding_count: 16,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: theology, philosophy',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 92,
    triage_run_at: '2026-02-15T14:10:00Z',
    physical_location: 'Shelf C1',
    acquisition_cost: 2.0,
    acquisition_date: '2026-02-12',
    acquisition_source: 'YMCA Charity Shop, Edinburgh',
    condition: 'fair',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-02-12', detail: 'YMCA Charity Shop, Edinburgh', cost: 2.0 },
      { event: 'Triage', date: '2026-02-15', detail: 'SCAN & SELL DATA — score 92' },
    ],
    created_at: '2026-02-15T14:00:00Z',
    updated_at: '2026-02-15T14:10:00Z',
  },
  {
    id: 'b1a2c3d4-0006-4000-8000-000000000006',
    isbn: '9780000334455',
    title: 'A Treatise on the Strength of Materials and Structures',
    subtitle: 'For Civil and Mechanical Engineers',
    author_name: 'William Hesketh Lorne CE',
    author_birth_year: 1855,
    author_death_year: 1930,
    publisher: 'E. & F. N. Spon',
    publish_year: 1909,
    publish_date_exact: null,
    language: 'en',
    page_count: 498,
    genre: 'Engineering',
    subject_keywords: ['engineering', 'structures', 'mechanics', 'materials', 'civil engineering'],
    description:
      'An authoritative text on structural engineering covering stress analysis, beam theory, column design, and materials testing, written from decades of practical consulting experience.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1930, UK PD since 2000 (life + 70 years).',
    public_domain_checked_at: '2026-02-20T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: 'OL345678M',
    openlibrary_url: 'https://openlibrary.org/books/OL345678M',
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 20,
    ai_training_value: 'high',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: engineering',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 80,
    triage_run_at: '2026-02-20T10:10:00Z',
    physical_location: 'Shelf C2',
    acquisition_cost: 4.5,
    acquisition_date: '2026-02-18',
    acquisition_source: 'Amnesty International Bookshop, Brighton',
    condition: 'very_good',
    scan_status: 'scanning',
    scan_method: 'flatbed',
    scan_started_at: '2026-02-22T08:00:00Z',
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-02-18', detail: 'Amnesty International Bookshop, Brighton', cost: 4.5 },
      { event: 'Triage', date: '2026-02-20', detail: 'SCAN & SELL DATA — score 80' },
    ],
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-02-22T08:00:00Z',
  },
  {
    id: 'b1a2c3d4-0007-4000-8000-000000000007',
    isbn: '9780000445566',
    title: 'The Cultivation of the Potato and Root Crops',
    subtitle: 'A Practical Handbook for British Farmers',
    author_name: 'Ebenezer Croft Stanmore',
    author_birth_year: 1860,
    author_death_year: 1935,
    publisher: 'Vinton & Co.',
    publish_year: 1903,
    publish_date_exact: null,
    language: 'en',
    page_count: 284,
    genre: 'Agriculture',
    subject_keywords: ['agriculture', 'farming', 'root crops', 'potato', 'soil science'],
    description:
      'A practical guide to British arable farming focusing on potato and turnip cultivation, soil preparation, drainage, pest management, and yield optimisation on mixed farms.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1935, UK PD since 2005 (life + 70 years).',
    public_domain_checked_at: '2026-03-01T09:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'very_rare',
    worldcat_holding_count: 5,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: agriculture',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: 'Only 5 WorldCat holdings — exceptionally rare.',
    triage_score: 98,
    triage_run_at: '2026-03-01T09:10:00Z',
    physical_location: 'Shelf D1',
    acquisition_cost: 1.5,
    acquisition_date: '2026-02-28',
    acquisition_source: 'Sue Ryder, Norwich',
    condition: 'fair',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-02-28', detail: 'Sue Ryder, Norwich', cost: 1.5 },
      { event: 'Triage', date: '2026-03-01', detail: 'SCAN & SELL DATA — score 98' },
    ],
    created_at: '2026-03-01T09:00:00Z',
    updated_at: '2026-03-01T09:10:00Z',
  },
  {
    id: 'b1a2c3d4-0008-4000-8000-000000000008',
    isbn: '9780000556677',
    title: 'Contributions to the History of British Law',
    subtitle: null,
    author_name: 'Sir Barnaby Ashworth Pelham KC',
    author_birth_year: 1843,
    author_death_year: 1919,
    publisher: 'Sweet & Maxwell',
    publish_year: 1896,
    publish_date_exact: null,
    language: 'en',
    page_count: 380,
    genre: 'Law',
    subject_keywords: ['law', 'legal history', 'common law', 'equity', 'jurisprudence'],
    description:
      'A series of scholarly essays tracing the development of English common law from the Norman Conquest through the Victorian era, drawing on unpublished manuscript sources.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1919, UK PD since 1989 (life + 70 years).',
    public_domain_checked_at: '2026-03-05T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'rare',
    worldcat_holding_count: 11,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: law',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 93,
    triage_run_at: '2026-03-05T10:10:00Z',
    physical_location: 'Shelf D2',
    acquisition_cost: 5.0,
    acquisition_date: '2026-03-03',
    acquisition_source: 'Hatchards Clearance Sale, London',
    condition: 'good',
    scan_status: 'reviewed',
    scan_method: 'document_scanner',
    scan_started_at: '2026-03-08T09:00:00Z',
    scan_completed_at: '2026-03-10T12:00:00Z',
    ocr_text_path: '/ocr-text/b1a2c3d4-0008.txt',
    ocr_quality_score: 0.91,
    ocr_word_count: 112_000,
    ocr_page_count: 380,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-03-03', detail: 'Hatchards Clearance Sale, London', cost: 5.0 },
      { event: 'Triage', date: '2026-03-05', detail: 'SCAN & SELL DATA — score 93' },
      { event: 'Scan', date: '2026-03-08', detail: 'Document scanner', method: 'document_scanner', quality: 0.91 },
    ],
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-03-10T12:00:00Z',
  },
  {
    id: 'b1a2c3d4-0009-4000-8000-000000000009',
    isbn: '9780000667788',
    title: 'Astronomical Observations at Greenwich 1875–1880',
    subtitle: 'Volume III: Planetary Positions and Solar Parallax',
    author_name: 'Sir George Bramwell Staughton FRS',
    author_birth_year: 1839,
    author_death_year: 1907,
    publisher: 'HM Stationery Office',
    publish_year: 1882,
    publish_date_exact: null,
    language: 'en',
    page_count: 962,
    genre: 'Astronomy',
    subject_keywords: ['astronomy', 'planetary science', 'observation', 'Greenwich', 'solar system'],
    description:
      'The third volume of the official Greenwich Observatory observation record, containing tabulated planetary positions, solar parallax measurements, and systematic error analyses.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1907, UK PD since 1977 (life + 70 years).',
    public_domain_checked_at: '2026-03-10T11:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'unique',
    worldcat_holding_count: 3,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: astronomy, mathematics',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: 'Unique copy — 3 WorldCat holdings globally.',
    triage_score: 100,
    triage_run_at: '2026-03-10T11:10:00Z',
    physical_location: 'Special Storage',
    acquisition_cost: 7.5,
    acquisition_date: '2026-03-08',
    acquisition_source: 'Auction — Lyon & Turnbull, Edinburgh',
    condition: 'very_good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-03-08', detail: 'Auction — Lyon & Turnbull, Edinburgh', cost: 7.5 },
      { event: 'Triage', date: '2026-03-10', detail: 'SCAN & SELL DATA — score 100' },
    ],
    created_at: '2026-03-10T11:00:00Z',
    updated_at: '2026-03-10T11:10:00Z',
  },
  {
    id: 'b1a2c3d4-0010-4000-8000-000000000010',
    isbn: '9780000778899',
    title: 'A Manual of Elementary Physics',
    subtitle: 'With Numerical Examples',
    author_name: 'Harold Dunstable Forsythe BSc',
    author_birth_year: 1878,
    author_death_year: 1950,
    publisher: 'Cambridge University Press',
    publish_year: 1930,
    publish_date_exact: null,
    language: 'en',
    page_count: 336,
    genre: 'Physics',
    subject_keywords: ['physics', 'mechanics', 'electricity', 'magnetism', 'thermodynamics'],
    description:
      'An introductory physics textbook for first-year university students covering classical mechanics, heat, electricity, and magnetism, with worked numerical examples throughout.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1950, UK PD since 2020 (life + 70 years).',
    public_domain_checked_at: '2026-03-15T09:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: 'OL456789M',
    openlibrary_url: 'https://openlibrary.org/books/OL456789M',
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 27,
    ai_training_value: 'high',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: physics, mathematics',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 80,
    triage_run_at: '2026-03-15T09:10:00Z',
    physical_location: 'Shelf E1',
    acquisition_cost: 2.5,
    acquisition_date: '2026-03-13',
    acquisition_source: 'Scope, Bath',
    condition: 'good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-03-13', detail: 'Scope, Bath', cost: 2.5 },
      { event: 'Triage', date: '2026-03-15', detail: 'SCAN & SELL DATA — score 80' },
    ],
    created_at: '2026-03-15T09:00:00Z',
    updated_at: '2026-03-15T09:10:00Z',
  },
  {
    id: 'b1a2c3d4-0011-4000-8000-000000000011',
    isbn: '9780000889900',
    title: "Gray's Anatomy of the Human Body",
    subtitle: 'Twenty-Second Edition',
    author_name: 'Henry Gray FRS',
    author_birth_year: 1827,
    author_death_year: 1861,
    publisher: 'Longmans, Green and Co.',
    publish_year: 1918,
    publish_date_exact: null,
    language: 'en',
    page_count: 1396,
    genre: 'Medicine',
    subject_keywords: ['anatomy', 'medicine', 'human body', 'surgery', 'physiology'],
    description:
      'The twenty-second edition of the definitive anatomical atlas, heavily revised by Warren H. Lewis, containing over 1,200 illustrations with detailed descriptions of every structure of the human body.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Original author Henry Gray died 1861, UK PD since 1931. This edition editor also long deceased.',
    public_domain_checked_at: '2026-03-20T10:00:00Z',
    gutenberg_id: 39258,
    gutenberg_url: 'https://www.gutenberg.org/ebooks/39258',
    openlibrary_id: 'OL567890M',
    openlibrary_url: 'https://openlibrary.org/books/OL567890M',
    already_digitised: true,
    digitised_source: 'Project Gutenberg',
    estimated_copies_surviving: 'common',
    worldcat_holding_count: 512,
    ai_training_value: 'medium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'already on Gutenberg — lower uniqueness value',
    ],
    pre_llm_era: true,
    triage_action: 'already_available',
    triage_notes: 'This edition is on Gutenberg. Sell the physical copy only.',
    triage_score: 35,
    triage_run_at: '2026-03-20T10:10:00Z',
    physical_location: 'Shelf F1',
    acquisition_cost: 3.0,
    acquisition_date: '2026-03-18',
    acquisition_source: 'Redcross, Manchester',
    condition: 'fair',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'listed',
    resale_platform: 'ebay',
    resale_price: 12.99,
    resale_listed_at: '2026-03-21T09:00:00Z',
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-03-18', detail: 'Redcross, Manchester', cost: 3.0 },
      { event: 'Triage', date: '2026-03-20', detail: 'ALREADY AVAILABLE — score 35' },
      { event: 'Listed for resale', date: '2026-03-21', detail: 'eBay', platform: 'ebay', price: 12.99 },
    ],
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-21T09:00:00Z',
  },
  {
    id: 'b1a2c3d4-0012-4000-8000-000000000012',
    isbn: '9780000990011',
    title: 'The Metaphysics of Natural Law',
    subtitle: null,
    author_name: 'Professor Cornelius Blake Stanton MA',
    author_birth_year: 1876,
    author_death_year: 1948,
    publisher: 'Oxford University Press',
    publish_year: 1935,
    publish_date_exact: null,
    language: 'en',
    page_count: 302,
    genre: 'Philosophy',
    subject_keywords: ['philosophy', 'metaphysics', 'natural law', 'ethics', 'jurisprudence'],
    description:
      'An influential monograph on the philosophical foundations of natural law theory, examining its relation to positive law and moral obligation in the tradition of British analytical philosophy.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1948, UK PD since 2018 (life + 70 years).',
    public_domain_checked_at: '2026-04-01T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'rare',
    worldcat_holding_count: 14,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: philosophy, law',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 88,
    triage_run_at: '2026-04-01T10:10:00Z',
    physical_location: 'Shelf G1',
    acquisition_cost: 4.0,
    acquisition_date: '2026-03-30',
    acquisition_source: 'Oxfam Bookshop, Oxford',
    condition: 'very_good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-03-30', detail: 'Oxfam Bookshop, Oxford', cost: 4.0 },
      { event: 'Triage', date: '2026-04-01', detail: 'SCAN & SELL DATA — score 88' },
    ],
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-04-01T10:10:00Z',
  },
  {
    id: 'b1a2c3d4-0013-4000-8000-000000000013',
    isbn: '9780001112233',
    title: 'Diseases of the Nervous System',
    subtitle: 'A Textbook for Practitioners',
    author_name: 'Dr Hubert Montague Alston MD FRCP',
    author_birth_year: 1868,
    author_death_year: 1942,
    publisher: 'Henry Kimpton',
    publish_year: 1926,
    publish_date_exact: null,
    language: 'en',
    page_count: 604,
    genre: 'Medicine',
    subject_keywords: ['medicine', 'neurology', 'nervous system', 'clinical medicine', 'psychiatry'],
    description:
      'A clinical reference for general practitioners on disorders of the nervous system, covering epilepsy, paralysis, neuritis, and early 20th-century treatment approaches.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1942, UK PD since 2012 (life + 70 years).',
    public_domain_checked_at: '2026-04-05T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 19,
    ai_training_value: 'high',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: medicine',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 78,
    triage_run_at: '2026-04-05T10:10:00Z',
    physical_location: 'Shelf G2',
    acquisition_cost: 3.5,
    acquisition_date: '2026-04-03',
    acquisition_source: 'Cancer Research UK, Leeds',
    condition: 'good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-04-03', detail: 'Cancer Research UK, Leeds', cost: 3.5 },
      { event: 'Triage', date: '2026-04-05', detail: 'SCAN & SELL DATA — score 78' },
    ],
    created_at: '2026-04-05T10:00:00Z',
    updated_at: '2026-04-05T10:10:00Z',
  },
  {
    id: 'b1a2c3d4-0014-4000-8000-000000000014',
    isbn: '9780001223344',
    title: 'The Novels of Charles Dickens: A Critical Survey',
    subtitle: null,
    author_name: 'Margaret Louisa Thornycroft',
    author_birth_year: 1885,
    author_death_year: 1960,
    publisher: 'Duckworth',
    publish_year: 1938,
    publish_date_exact: null,
    language: 'en',
    page_count: 268,
    genre: 'Literary Criticism',
    subject_keywords: ['literary criticism', 'Victorian literature', 'Dickens', 'novel', 'English literature'],
    description:
      'A critical examination of the major novels of Charles Dickens, analysing character, social critique, and narrative technique from a mid-century scholarly perspective.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1960, UK PD since 2030. Still in copyright as of 2026.',
    public_domain_checked_at: '2026-04-10T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'common',
    worldcat_holding_count: 88,
    ai_training_value: 'low',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'copyrighted — requires licensing',
    ],
    pre_llm_era: true,
    triage_action: 'sell_physical',
    triage_notes: 'Author died 1960 — still in UK copyright until 2030.',
    triage_score: 15,
    triage_run_at: '2026-04-10T10:10:00Z',
    physical_location: 'Shelf H1',
    acquisition_cost: 2.0,
    acquisition_date: '2026-04-08',
    acquisition_source: 'Oxfam Bookshop, Birmingham',
    condition: 'good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'listed',
    resale_platform: 'amazon',
    resale_price: 8.99,
    resale_listed_at: '2026-04-11T09:00:00Z',
    resale_sold_at: '2026-04-18T14:00:00Z',
    provenance_chain: [
      { event: 'Acquired', date: '2026-04-08', detail: 'Oxfam Bookshop, Birmingham', cost: 2.0 },
      { event: 'Triage', date: '2026-04-10', detail: 'SELL PHYSICAL — score 15' },
      { event: 'Listed for resale', date: '2026-04-11', detail: 'Amazon', platform: 'amazon', price: 8.99 },
      { event: 'Sold', date: '2026-04-18', detail: 'Amazon sale completed', platform: 'amazon', price: 8.99 },
    ],
    created_at: '2026-04-10T10:00:00Z',
    updated_at: '2026-04-18T14:00:00Z',
  },
  {
    id: 'b1a2c3d4-0015-4000-8000-000000000015',
    isbn: '9780001334455',
    title: 'Algebra for Schools and Colleges',
    subtitle: null,
    author_name: 'Clifford Hugh Warburton MA',
    author_birth_year: 1890,
    author_death_year: 1955,
    publisher: 'George Bell and Sons',
    publish_year: 1932,
    publish_date_exact: null,
    language: 'en',
    page_count: 410,
    genre: 'Mathematics',
    subject_keywords: ['mathematics', 'algebra', 'arithmetic', 'equations', 'school mathematics'],
    description:
      'A comprehensive algebra textbook for secondary and further education, covering arithmetic progressions, binomial theorem, determinants, and introductory calculus with abundant exercises.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1955, UK PD since 2025 (life + 70 years).',
    public_domain_checked_at: '2026-04-15T09:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 35,
    ai_training_value: 'high',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: mathematics',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 77,
    triage_run_at: '2026-04-15T09:10:00Z',
    physical_location: 'Shelf I1',
    acquisition_cost: 2.5,
    acquisition_date: '2026-04-13',
    acquisition_source: 'Barnardos, Cheltenham',
    condition: 'good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-04-13', detail: 'Barnardos, Cheltenham', cost: 2.5 },
      { event: 'Triage', date: '2026-04-15', detail: 'SCAN & SELL DATA — score 77' },
    ],
    created_at: '2026-04-15T09:00:00Z',
    updated_at: '2026-04-15T09:10:00Z',
  },
  {
    id: 'b1a2c3d4-0016-4000-8000-000000000016',
    isbn: '9780001445566',
    title: 'Entomology and the British Insect Fauna',
    subtitle: 'A Guide for Collectors and Naturalists',
    author_name: 'Frederick Jasper Blunt FES',
    author_birth_year: 1862,
    author_death_year: 1933,
    publisher: 'Methuen & Co.',
    publish_year: 1908,
    publish_date_exact: null,
    language: 'en',
    page_count: 524,
    genre: 'Natural History',
    subject_keywords: ['biology', 'entomology', 'insects', 'natural history', 'taxonomy'],
    description:
      'A comprehensive guide to identifying and collecting British insects, covering all major orders with detailed keys, habitat notes, and collecting techniques for the amateur naturalist.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1933, UK PD since 2003 (life + 70 years).',
    public_domain_checked_at: '2026-04-20T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'very_rare',
    worldcat_holding_count: 7,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: biology',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: 'Very rare. 7 WorldCat holdings.',
    triage_score: 96,
    triage_run_at: '2026-04-20T10:10:00Z',
    physical_location: 'Shelf J1',
    acquisition_cost: 6.0,
    acquisition_date: '2026-04-18',
    acquisition_source: 'Albion Rare Books, York',
    condition: 'good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-04-18', detail: 'Albion Rare Books, York', cost: 6.0 },
      { event: 'Triage', date: '2026-04-20', detail: 'SCAN & SELL DATA — score 96' },
    ],
    created_at: '2026-04-20T10:00:00Z',
    updated_at: '2026-04-20T10:10:00Z',
  },
  {
    id: 'b1a2c3d4-0017-4000-8000-000000000017',
    isbn: '9780001556677',
    title: "A History of British Commerce 1560–1850",
    subtitle: null,
    author_name: 'Professor Duncan Alistair Forsgate',
    author_birth_year: 1888,
    author_death_year: 1952,
    publisher: 'John Murray',
    publish_year: 1940,
    publish_date_exact: null,
    language: 'en',
    page_count: 446,
    genre: 'History',
    subject_keywords: ['history', 'economics', 'trade', 'British Empire', 'commerce'],
    description:
      'A detailed economic history tracing the growth of British trade from the Elizabethan era through to the Great Exhibition, drawing on primary sources from the Board of Trade archives.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1952, UK PD since 2022 (life + 70 years).',
    public_domain_checked_at: '2026-04-25T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'uncommon',
    worldcat_holding_count: 42,
    ai_training_value: 'high',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: history',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: null,
    triage_score: 76,
    triage_run_at: '2026-04-25T10:10:00Z',
    physical_location: 'Shelf K1',
    acquisition_cost: 3.5,
    acquisition_date: '2026-04-23',
    acquisition_source: "Waterstones Clearance, Bath",
    condition: 'very_good',
    scan_status: 'not_scanned',
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-04-23', detail: "Waterstones Clearance, Bath", cost: 3.5 },
      { event: 'Triage', date: '2026-04-25', detail: 'SCAN & SELL DATA — score 76' },
    ],
    created_at: '2026-04-25T10:00:00Z',
    updated_at: '2026-04-25T10:10:00Z',
  },
  {
    id: 'b1a2c3d4-0018-4000-8000-000000000018',
    isbn: '9780001667788',
    title: 'Church Architecture from the Anglo-Saxon Period',
    subtitle: 'Volume I: Pre-Norman and Early Norman',
    author_name: 'Godfrey Elton Radstock ARIBA',
    author_birth_year: 1844,
    author_death_year: 1916,
    publisher: 'B. T. Batsford',
    publish_year: 1894,
    publish_date_exact: null,
    language: 'en',
    page_count: 326,
    genre: 'Architecture',
    subject_keywords: ['history', 'architecture', 'church architecture', 'Anglo-Saxon', 'Norman'],
    description:
      'The first volume of a scholarly survey of English ecclesiastical architecture from the 7th to 12th centuries, featuring original measured drawings, plans, and documentary evidence from church records.',
    public_domain_status: 'confirmed_pd',
    public_domain_reason: 'Author died 1916, UK PD since 1986 (life + 70 years).',
    public_domain_checked_at: '2026-05-01T10:00:00Z',
    gutenberg_id: null,
    gutenberg_url: null,
    openlibrary_id: null,
    openlibrary_url: null,
    already_digitised: false,
    digitised_source: null,
    estimated_copies_surviving: 'very_rare',
    worldcat_holding_count: 6,
    ai_training_value: 'premium',
    ai_value_factors: [
      'pre-LLM era (pre-2022)',
      'public domain — no licensing needed',
      'not on Gutenberg — potentially unique data',
      'niche domain: history, engineering',
    ],
    pre_llm_era: true,
    triage_action: 'scan_and_sell_data',
    triage_notes: 'Very rare architectural survey. 6 WorldCat holdings.',
    triage_score: 94,
    triage_run_at: '2026-05-01T10:10:00Z',
    physical_location: 'Shelf L1',
    acquisition_cost: 4.5,
    acquisition_date: '2026-04-29',
    acquisition_source: 'Bloomsbury Auctions, London',
    condition: 'very_good',
    scan_status: 'preserve_only' as unknown as Book['scan_status'],
    scan_method: null,
    scan_started_at: null,
    scan_completed_at: null,
    ocr_text_path: null,
    ocr_quality_score: null,
    ocr_word_count: null,
    ocr_page_count: null,
    resale_status: 'not_listed',
    resale_platform: null,
    resale_price: null,
    resale_listed_at: null,
    resale_sold_at: null,
    provenance_chain: [
      { event: 'Acquired', date: '2026-04-29', detail: 'Bloomsbury Auctions, London', cost: 4.5 },
      { event: 'Triage', date: '2026-05-01', detail: 'SCAN & SELL DATA — score 94' },
    ],
    created_at: '2026-05-01T10:00:00Z',
    updated_at: '2026-05-01T10:10:00Z',
  },
];

// Fix the scan_status for book 0018 (it can't be 'preserve_only')
MOCK_BOOKS[MOCK_BOOKS.length - 1]!.scan_status = 'not_scanned';

// ── Datasets ──────────────────────────────────────────────────────────────────

export const MOCK_DATASETS: Dataset[] = [
  {
    id: 'ds-0001-0000-0000-000000000001',
    book_id: 'b1a2c3d4-0001-4000-8000-000000000001',
    title: 'Hayward Botany 1905 — OCR Dataset',
    description: 'Full OCR text of a rare 1905 botany monograph covering the natural system of plant classification. 187,000+ words of clean scientific English.',
    domain_tags: ['botany', 'natural history', 'taxonomy'],
    language: 'en',
    word_count: 187_420,
    page_count: 614,
    text_file_path: '/ocr-text/b1a2c3d4-0001.txt',
    text_preview: 'The classification of plants into natural orders has occupied the minds of systematic botanists since the early works of Ray and Tournefort...',
    ocr_quality_score: 0.94,
    provenance_document: { source: 'original physical copy', acquisition: 'Oxfam Cambridge 2025', scan_method: 'document_scanner' },
    sale_status: 'listed',
    asking_price: 280.0,
    final_price: null,
    listed_platform: 'defined_ai',
    listed_url: 'https://defined.ai/datasets/hayward-botany-1905',
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    listed_at: '2026-01-20T10:00:00Z',
    sold_at: null,
    created_at: '2026-01-16T09:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'ds-0002-0000-0000-000000000002',
    book_id: 'b1a2c3d4-0008-4000-8000-000000000008',
    title: 'Pelham British Legal History — OCR Dataset',
    description: 'Scholarly legal history essays from 1896, covering common law development from the Norman period. 112,000 words of dense academic prose.',
    domain_tags: ['law', 'legal history', 'history'],
    language: 'en',
    word_count: 112_000,
    page_count: 380,
    text_file_path: '/ocr-text/b1a2c3d4-0008.txt',
    text_preview: 'The development of the common law of England from its origins in the feudal customs of the Normans to its modern form...',
    ocr_quality_score: 0.91,
    provenance_document: { source: 'original physical copy', acquisition: 'Hatchards London 2026', scan_method: 'document_scanner' },
    sale_status: 'sold',
    asking_price: 210.0,
    final_price: 195.0,
    listed_platform: 'direct',
    listed_url: null,
    buyer_name: 'Meridian AI Ltd',
    buyer_type: 'ai_lab',
    nda_signed: true,
    listed_at: '2026-03-12T10:00:00Z',
    sold_at: '2026-03-28T15:00:00Z',
    created_at: '2026-03-11T09:00:00Z',
    updated_at: '2026-03-28T15:00:00Z',
  },
  {
    id: 'ds-0003-0000-0000-000000000003',
    book_id: 'b1a2c3d4-0002-4000-8000-000000000002',
    title: 'Pryce Nautical Astronomy 1888 — OCR Dataset',
    description: 'Complete OCR of a rare 1888 RN navigation manual. Tables, worked examples, and theoretical treatise on celestial navigation. 142,800 words.',
    domain_tags: ['navigation', 'astronomy', 'mathematics'],
    language: 'en',
    word_count: 142_800,
    page_count: 452,
    text_file_path: '/ocr-text/b1a2c3d4-0002.txt',
    text_preview: 'The art of navigation at sea consists in determining the position of the ship at any given moment by celestial observation...',
    ocr_quality_score: 0.89,
    provenance_document: { source: 'original physical copy', acquisition: 'Hay-on-Wye 2026', scan_method: 'dslr' },
    sale_status: 'negotiating',
    asking_price: 360.0,
    final_price: null,
    listed_platform: 'aws_data_exchange',
    listed_url: null,
    buyer_name: 'Lighthouse Data Corp',
    buyer_type: 'data_broker',
    nda_signed: false,
    listed_at: '2026-01-25T10:00:00Z',
    sold_at: null,
    created_at: '2026-01-22T09:00:00Z',
    updated_at: '2026-01-25T10:00:00Z',
  },
  {
    id: 'ds-0004-0000-0000-000000000004',
    book_id: 'b1a2c3d4-0004-4000-8000-000000000004',
    title: 'Hartley Materia Medica 1914 — OCR Dataset',
    description: 'Edwardian pharmacological reference covering drug actions, dosage tables, and therapeutic applications. 160,000 words of medical English.',
    domain_tags: ['medicine', 'pharmacology'],
    language: 'en',
    word_count: 160_000,
    page_count: 542,
    text_file_path: null as unknown as string,
    text_preview: null,
    ocr_quality_score: null,
    provenance_document: {},
    sale_status: 'not_listed',
    asking_price: 240.0,
    final_price: null,
    listed_platform: null,
    listed_url: null,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    listed_at: null,
    sold_at: null,
    created_at: '2026-02-11T10:00:00Z',
    updated_at: '2026-02-11T10:00:00Z',
  },
  {
    id: 'ds-0005-0000-0000-000000000005',
    book_id: 'b1a2c3d4-0005-4000-8000-000000000005',
    title: 'Finbury Systematic Theology 1899 — OCR Dataset',
    description: 'Late-Victorian philosophical theology engaging Hegel and Kant. 220,000 words of dense philosophical prose from 1899.',
    domain_tags: ['theology', 'philosophy'],
    language: 'en',
    word_count: 220_000,
    page_count: 720,
    text_file_path: null as unknown as string,
    text_preview: null,
    ocr_quality_score: null,
    provenance_document: {},
    sale_status: 'not_listed',
    asking_price: 320.0,
    final_price: null,
    listed_platform: null,
    listed_url: null,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    listed_at: null,
    sold_at: null,
    created_at: '2026-02-16T10:00:00Z',
    updated_at: '2026-02-16T10:00:00Z',
  },
  {
    id: 'ds-0006-0000-0000-000000000006',
    book_id: 'b1a2c3d4-0012-4000-8000-000000000012',
    title: 'Stanton Natural Law 1935 — OCR Dataset',
    description: 'Influential 1935 Oxford monograph on natural law theory. 90,000 words of analytical philosophy in clear, precise academic English.',
    domain_tags: ['philosophy', 'law', 'ethics'],
    language: 'en',
    word_count: 90_000,
    page_count: 302,
    text_file_path: null as unknown as string,
    text_preview: null,
    ocr_quality_score: null,
    provenance_document: {},
    sale_status: 'not_listed',
    asking_price: 185.0,
    final_price: null,
    listed_platform: null,
    listed_url: null,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    listed_at: null,
    sold_at: null,
    created_at: '2026-04-02T10:00:00Z',
    updated_at: '2026-04-02T10:00:00Z',
  },
];

// ── Sales ─────────────────────────────────────────────────────────────────────

export const MOCK_SALES: Sale[] = [
  // Data sales
  {
    id: 'sale-0001-0000-0000-000000000001',
    book_id: 'b1a2c3d4-0008-4000-8000-000000000008',
    dataset_id: 'ds-0002-0000-0000-000000000002',
    sale_type: 'data',
    platform: 'direct',
    listing_url: null,
    asking_price: 210.0,
    final_price: 195.0,
    buyer_name: 'Meridian AI Ltd',
    buyer_type: 'ai_lab',
    nda_signed: true,
    status: 'sold',
    listed_at: '2026-03-12T10:00:00Z',
    sold_at: '2026-03-28T15:00:00Z',
    notes: 'Direct negotiation. NDA signed.',
    created_at: '2026-03-12T10:00:00Z',
    book_title: 'Contributions to the History of British Law',
  },
  {
    id: 'sale-0002-0000-0000-000000000002',
    book_id: 'b1a2c3d4-0001-4000-8000-000000000001',
    dataset_id: 'ds-0001-0000-0000-000000000001',
    sale_type: 'data',
    platform: 'hugging_face',
    listing_url: 'https://huggingface.co/datasets/bookscan/hayward-botany',
    asking_price: 280.0,
    final_price: 265.0,
    buyer_name: 'OpenBio Ventures',
    buyer_type: 'biotech',
    nda_signed: false,
    status: 'sold',
    listed_at: '2026-02-10T10:00:00Z',
    sold_at: '2026-02-24T11:00:00Z',
    notes: null,
    created_at: '2026-02-10T10:00:00Z',
    book_title: 'A Complete System of Botany',
  },
  {
    id: 'sale-0003-0000-0000-000000000003',
    book_id: null,
    dataset_id: null,
    sale_type: 'data',
    platform: 'defined_ai',
    listing_url: null,
    asking_price: 450.0,
    final_price: 420.0,
    buyer_name: 'Axiom Language Technologies',
    buyer_type: 'nlp_lab',
    nda_signed: true,
    status: 'sold',
    listed_at: '2026-01-15T10:00:00Z',
    sold_at: '2026-01-30T16:00:00Z',
    notes: 'Astronomy dataset — exceptional demand.',
    created_at: '2026-01-15T10:00:00Z',
    book_title: 'Astronomical Observations at Greenwich 1875–1880',
  },
  {
    id: 'sale-0004-0000-0000-000000000004',
    book_id: null,
    dataset_id: null,
    sale_type: 'data',
    platform: 'aws_data_exchange',
    listing_url: null,
    asking_price: 310.0,
    final_price: 310.0,
    buyer_name: 'CloudMind Analytics',
    buyer_type: 'ai_lab',
    nda_signed: false,
    status: 'sold',
    listed_at: '2025-12-01T10:00:00Z',
    sold_at: '2025-12-15T14:00:00Z',
    notes: null,
    created_at: '2025-12-01T10:00:00Z',
    book_title: 'Practical Navigation and Nautical Astronomy',
  },
  {
    id: 'sale-0005-0000-0000-000000000005',
    book_id: null,
    dataset_id: null,
    sale_type: 'data',
    platform: 'direct',
    listing_url: null,
    asking_price: 180.0,
    final_price: 175.0,
    buyer_name: 'Phronesis Research Ltd',
    buyer_type: 'university',
    nda_signed: false,
    status: 'sold',
    listed_at: '2026-04-01T10:00:00Z',
    sold_at: '2026-04-10T10:00:00Z',
    notes: 'University research licence.',
    created_at: '2026-04-01T10:00:00Z',
    book_title: 'The Principles of Organic Chemistry',
  },
  {
    id: 'sale-0006-0000-0000-000000000006',
    book_id: null,
    dataset_id: null,
    sale_type: 'data',
    platform: 'hugging_face',
    listing_url: null,
    asking_price: 390.0,
    final_price: 375.0,
    buyer_name: 'Verdant ML',
    buyer_type: 'ai_lab',
    nda_signed: true,
    status: 'sold',
    listed_at: '2025-11-01T10:00:00Z',
    sold_at: '2025-11-20T10:00:00Z',
    notes: null,
    created_at: '2025-11-01T10:00:00Z',
    book_title: 'A Treatise on the Strength of Materials',
  },
  {
    id: 'sale-0007-0000-0000-000000000007',
    book_id: null,
    dataset_id: null,
    sale_type: 'data',
    platform: 'defined_ai',
    listing_url: null,
    asking_price: 220.0,
    final_price: 210.0,
    buyer_name: 'BioCorpus AI',
    buyer_type: 'biotech',
    nda_signed: false,
    status: 'sold',
    listed_at: '2025-10-05T10:00:00Z',
    sold_at: '2025-10-18T14:00:00Z',
    notes: null,
    created_at: '2025-10-05T10:00:00Z',
    book_title: 'Materia Medica and Therapeutics',
  },
  // Physical sales
  {
    id: 'sale-0008-0000-0000-000000000008',
    book_id: 'b1a2c3d4-0014-4000-8000-000000000014',
    dataset_id: null,
    sale_type: 'physical',
    platform: 'amazon',
    listing_url: null,
    asking_price: 8.99,
    final_price: 8.99,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2026-04-11T09:00:00Z',
    sold_at: '2026-04-18T14:00:00Z',
    notes: null,
    created_at: '2026-04-11T09:00:00Z',
    book_title: 'The Novels of Charles Dickens',
  },
  {
    id: 'sale-0009-0000-0000-000000000009',
    book_id: null,
    dataset_id: null,
    sale_type: 'physical',
    platform: 'abebooks',
    listing_url: null,
    asking_price: 22.0,
    final_price: 22.0,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2026-03-05T09:00:00Z',
    sold_at: '2026-03-12T11:00:00Z',
    notes: null,
    created_at: '2026-03-05T09:00:00Z',
    book_title: 'A Complete System of Botany (physical)',
  },
  {
    id: 'sale-0010-0000-0000-000000000010',
    book_id: null,
    dataset_id: null,
    sale_type: 'physical',
    platform: 'ebay',
    listing_url: null,
    asking_price: 15.0,
    final_price: 14.5,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2025-12-10T09:00:00Z',
    sold_at: '2025-12-22T14:00:00Z',
    notes: null,
    created_at: '2025-12-10T09:00:00Z',
    book_title: 'Gray\'s Anatomy 22nd Edition',
  },
  {
    id: 'sale-0011-0000-0000-000000000011',
    book_id: null,
    dataset_id: null,
    sale_type: 'physical',
    platform: 'abebooks',
    listing_url: null,
    asking_price: 35.0,
    final_price: 32.0,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2025-11-15T09:00:00Z',
    sold_at: '2025-11-28T11:00:00Z',
    notes: null,
    created_at: '2025-11-15T09:00:00Z',
    book_title: 'Systematic Theology',
  },
  {
    id: 'sale-0012-0000-0000-000000000012',
    book_id: null,
    dataset_id: null,
    sale_type: 'physical',
    platform: 'amazon',
    listing_url: null,
    asking_price: 12.0,
    final_price: 11.5,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2026-01-08T09:00:00Z',
    sold_at: '2026-01-16T14:00:00Z',
    notes: null,
    created_at: '2026-01-08T09:00:00Z',
    book_title: 'Algebra for Schools',
  },
  {
    id: 'sale-0013-0000-0000-000000000013',
    book_id: null,
    dataset_id: null,
    sale_type: 'physical',
    platform: 'ziffit',
    listing_url: null,
    asking_price: 6.0,
    final_price: 6.0,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2025-10-10T09:00:00Z',
    sold_at: '2025-10-12T11:00:00Z',
    notes: 'Quick turnaround via Ziffit.',
    created_at: '2025-10-10T09:00:00Z',
    book_title: 'A History of British Commerce',
  },
  {
    id: 'sale-0014-0000-0000-000000000014',
    book_id: null,
    dataset_id: null,
    sale_type: 'physical',
    platform: 'ebay',
    listing_url: null,
    asking_price: 18.0,
    final_price: 17.0,
    buyer_name: null,
    buyer_type: null,
    nda_signed: false,
    status: 'sold',
    listed_at: '2026-02-20T09:00:00Z',
    sold_at: '2026-03-01T11:00:00Z',
    notes: null,
    created_at: '2026-02-20T09:00:00Z',
    book_title: 'Church Architecture from the Anglo-Saxon Period',
  },
];

// ── Derived stats — must match the sales/book arrays above ────────────────────

// Data revenue sum: 195 + 265 + 420 + 310 + 175 + 375 + 210 = 1950
// Physical revenue sum: 8.99 + 22 + 14.5 + 32 + 11.5 + 6 + 17 = 111.99
const DATA_REVENUE = 1950;
const PHYSICAL_REVENUE = 111.99;
const TOTAL_REVENUE = DATA_REVENUE + PHYSICAL_REVENUE;
const TOTAL_ACQUISITION = MOCK_BOOKS.reduce((s, b) => s + (b.acquisition_cost ?? 0), 0);

export const MOCK_STATS: StatsSummary = {
  total_books: MOCK_BOOKS.length,
  public_domain_books: MOCK_BOOKS.filter(
    (b) => b.public_domain_status === 'confirmed_pd' || b.public_domain_status === 'likely_pd',
  ).length,
  public_domain_pct: Math.round(
    (MOCK_BOOKS.filter(
      (b) => b.public_domain_status === 'confirmed_pd' || b.public_domain_status === 'likely_pd',
    ).length /
      MOCK_BOOKS.length) *
      100,
  ),
  ready_to_scan: MOCK_BOOKS.filter((b) => b.triage_action === 'scan_and_sell_data' && b.scan_status === 'not_scanned').length,
  total_revenue: TOTAL_REVENUE,
  data_revenue: DATA_REVENUE,
  physical_revenue: PHYSICAL_REVENUE,
  total_acquisition_cost: TOTAL_ACQUISITION,
  net_profit: TOTAL_REVENUE - TOTAL_ACQUISITION,
  datasets_count: MOCK_DATASETS.length,
  datasets_sold: MOCK_DATASETS.filter((d) => d.sale_status === 'sold').length,
};

// ── Revenue summary — 12 months rolling ──────────────────────────────────────

const monthlyPoints: MonthlyRevenuePoint[] = [
  { month: '2025-08', label: 'Aug 25', data_revenue: 0,   physical_revenue: 0,   total: 0 },
  { month: '2025-09', label: 'Sep 25', data_revenue: 0,   physical_revenue: 0,   total: 0 },
  { month: '2025-10', label: 'Oct 25', data_revenue: 210, physical_revenue: 6,   total: 216 },
  { month: '2025-11', label: 'Nov 25', data_revenue: 375, physical_revenue: 32,  total: 407 },
  { month: '2025-12', label: 'Dec 25', data_revenue: 310, physical_revenue: 14.5, total: 324.5 },
  { month: '2026-01', label: 'Jan 26', data_revenue: 420 + 265, physical_revenue: 11.5, total: 697 },
  { month: '2026-02', label: 'Feb 26', data_revenue: 0,   physical_revenue: 17,  total: 17 },
  { month: '2026-03', label: 'Mar 26', data_revenue: 195, physical_revenue: 22,  total: 217 },
  { month: '2026-04', label: 'Apr 26', data_revenue: 175, physical_revenue: 8.99, total: 183.99 },
  { month: '2026-05', label: 'May 26', data_revenue: 0,   physical_revenue: 0,   total: 0 },
  { month: '2026-06', label: 'Jun 26', data_revenue: 0,   physical_revenue: 0,   total: 0 },
  { month: '2026-07', label: 'Jul 26', data_revenue: 0,   physical_revenue: 0,   total: 0 },
];

const platformSlices: PlatformRevenueSlice[] = [
  { platform: 'defined_ai', label: 'Defined.ai', revenue: 420 + 210, count: 2 },
  { platform: 'direct', label: 'Direct Sale', revenue: 195 + 175, count: 2 },
  { platform: 'hugging_face', label: 'Hugging Face', revenue: 265 + 375, count: 2 },
  { platform: 'aws_data_exchange', label: 'AWS Data Exchange', revenue: 310, count: 1 },
  { platform: 'abebooks', label: 'AbeBooks', revenue: 22 + 32, count: 2 },
  { platform: 'amazon', label: 'Amazon', revenue: 8.99 + 11.5, count: 2 },
  { platform: 'ebay', label: 'eBay', revenue: 14.5 + 17, count: 2 },
  { platform: 'ziffit', label: 'Ziffit', revenue: 6, count: 1 },
];

export const MOCK_REVENUE_SUMMARY: RevenueSummary = {
  total_revenue: TOTAL_REVENUE,
  data_revenue: DATA_REVENUE,
  physical_revenue: PHYSICAL_REVENUE,
  by_month: monthlyPoints,
  by_platform: platformSlices,
};

// ── Activity feed ─────────────────────────────────────────────────────────────

export const MOCK_ACTIVITY: ActivityEntry[] = [
  {
    id: uuid(),
    kind: 'book_added',
    title: 'Church Architecture from the Anglo-Saxon Period',
    detail: 'Score 94 · SCAN & SELL DATA',
    amount: null,
    timestamp: '2026-05-01T10:10:00Z',
  },
  {
    id: uuid(),
    kind: 'book_added',
    title: 'A History of British Commerce 1560–1850',
    detail: 'Score 76 · SCAN & SELL DATA',
    amount: null,
    timestamp: '2026-04-25T10:10:00Z',
  },
  {
    id: uuid(),
    kind: 'dataset_sold',
    title: 'Stanton Natural Law dataset',
    detail: 'Sold via Direct Sale to Phronesis Research',
    amount: 175.0,
    timestamp: '2026-04-10T10:00:00Z',
  },
  {
    id: uuid(),
    kind: 'book_sold',
    title: 'The Novels of Charles Dickens',
    detail: 'Physical sale via Amazon',
    amount: 8.99,
    timestamp: '2026-04-18T14:00:00Z',
  },
  {
    id: uuid(),
    kind: 'book_added',
    title: 'Diseases of the Nervous System',
    detail: 'Score 78 · SCAN & SELL DATA',
    amount: null,
    timestamp: '2026-04-05T10:10:00Z',
  },
  {
    id: uuid(),
    kind: 'dataset_sold',
    title: 'Pelham Legal History dataset',
    detail: 'Sold direct to Meridian AI Ltd',
    amount: 195.0,
    timestamp: '2026-03-28T15:00:00Z',
  },
  {
    id: uuid(),
    kind: 'book_sold',
    title: "A Complete System of Botany (physical)",
    detail: 'Physical sale via AbeBooks',
    amount: 22.0,
    timestamp: '2026-03-12T11:00:00Z',
  },
  {
    id: uuid(),
    kind: 'scan_complete',
    title: 'Contributions to the History of British Law',
    detail: 'OCR complete — quality 91%',
    amount: null,
    timestamp: '2026-03-10T12:00:00Z',
  },
  {
    id: uuid(),
    kind: 'dataset_sold',
    title: 'Hayward Botany dataset',
    detail: 'Sold via Hugging Face to OpenBio Ventures',
    amount: 265.0,
    timestamp: '2026-02-24T11:00:00Z',
  },
  {
    id: uuid(),
    kind: 'dataset_sold',
    title: 'Axiom astronomy dataset',
    detail: 'Sold via Defined.ai to Axiom Language Technologies',
    amount: 420.0,
    timestamp: '2026-01-30T16:00:00Z',
  },
];

// ── Triage distribution ───────────────────────────────────────────────────────

export const MOCK_TRIAGE_DISTRIBUTION: TriageDistributionSlice[] = [
  { action: 'scan_and_sell_data', label: 'Scan & Sell Data', count: MOCK_BOOKS.filter((b) => b.triage_action === 'scan_and_sell_data').length },
  { action: 'sell_physical', label: 'Sell Physical', count: MOCK_BOOKS.filter((b) => b.triage_action === 'sell_physical').length },
  { action: 'already_available', label: 'Already Available', count: MOCK_BOOKS.filter((b) => b.triage_action === 'already_available').length },
  { action: 'preserve_only', label: 'Preserve Only', count: MOCK_BOOKS.filter((b) => b.triage_action === 'preserve_only').length },
  { action: 'pending', label: 'Pending', count: MOCK_BOOKS.filter((b) => b.triage_action === 'pending').length },
];

// ── Triage history ────────────────────────────────────────────────────────────

export const MOCK_TRIAGE_HISTORY: TriageHistoryEntry[] = MOCK_BOOKS.slice(0, 10).map((b) => ({
  id: uuid(),
  isbn: b.isbn,
  title: b.title,
  author: b.author_name,
  triage_score: b.triage_score,
  triage_action: b.triage_action,
  created_at: b.triage_run_at ?? b.created_at,
}));

// ── Scan status (mock) ────────────────────────────────────────────────────────

export const MOCK_SCAN_STATUS = {
  book_id: 'b1a2c3d4-0001-4000-8000-000000000001',
  scan_status: 'ready_for_sale',
  scan_method: 'document_scanner',
  pages_uploaded: 614,
  pages_ocr_complete: 614,
  pages_reviewed: 614,
  ocr_quality_score: 0.94,
  ocr_word_count: 187_420,
  ocr_page_count: 614,
  progress_pct: 100,
  text_preview: 'The classification of plants into natural orders has occupied the minds of systematic botanists since the early works of Ray and Tournefort...',
};

// ── Mock triage result generator ─────────────────────────────────────────────

/**
 * Derive a deterministic-but-varied TriageResult from an ISBN or title string.
 * The result changes meaningfully with the input — different ISBNs give
 * different scores, PD statuses, and recommendations — so the triage demo page
 * is convincing without a live backend.
 */
export function mockTriageResult(seed: string): TriageResult {
  // Simple hash for determinism.
  let h = 0;
  for (let i = 0; i < seed.length; i++) {
    const c = seed.charCodeAt(i);
    h = (h << 5) - h + c;
    h |= 0;
  }
  const n = Math.abs(h);

  const titles = [
    'A Practical Treatise on Botanical Identification',
    'Principles of Electromagnetic Theory',
    'The Elements of Agricultural Chemistry',
    'Navigation and Pilotage for Maritime Officers',
    'Diseases of the Digestive System',
    'Contributions to the Study of British Bryophytes',
    'Fundamentals of Applied Mechanics',
    'The History and Practice of English Law',
  ] as const;

  const authors = [
    { name: 'Reginald Fortescue Hayward', birth: 1851, death: 1928 },
    { name: 'Professor Archibald Trent', birth: 1872, death: 1945 },
    { name: 'Dr Edmund Hartley', birth: 1865, death: 1938 },
    { name: 'Captain James Pryce RN', birth: 1840, death: 1912 },
    { name: 'Sir Barnaby Pelham KC', birth: 1843, death: 1919 },
    { name: 'Frederick Jasper Blunt', birth: 1862, death: 1933 },
    { name: 'William Hesketh Lorne', birth: 1855, death: 1930 },
    { name: 'Godfrey Elton Radstock', birth: 1844, death: 1916 },
  ] as const;

  const publishers = [
    'Chapman & Hall', 'Longmans, Green and Co.', 'J. & A. Churchill',
    'J. D. Potter', 'Sweet & Maxwell', 'Methuen & Co.',
    'E. & F. N. Spon', 'Oxford University Press',
  ] as const;

  const subjects = [
    ['botany', 'taxonomy', 'natural history'],
    ['physics', 'electromagnetism', 'engineering'],
    ['chemistry', 'agriculture', 'soil science'],
    ['navigation', 'astronomy', 'seamanship'],
    ['medicine', 'clinical', 'therapeutics'],
    ['biology', 'botany', 'natural history'],
    ['engineering', 'mechanics', 'structures'],
    ['law', 'legal history', 'jurisprudence'],
  ] as const;

  const idx = n % 8;
  const title = titles[idx] as string;
  const author = authors[idx]!;
  const publisher = publishers[idx] as string;
  const keywords = [...(subjects[idx] as readonly string[])];

  const publishYear = 1880 + (n % 60); // 1880–1939
  const deathYear = author.death;
  const pdYear = deathYear + 70;
  const currentYear = 2026;

  const isPd = currentYear > pdYear;
  const isLikelyPd = !isPd && publishYear < 1929;
  const pdStatus = isPd
    ? 'confirmed_pd'
    : isLikelyPd
    ? 'likely_pd'
    : 'not_pd';

  const pdReason = isPd
    ? `Author died ${deathYear}, UK public domain since ${pdYear} (life + 70 years).`
    : isLikelyPd
    ? `Published ${publishYear}. Pre-1929 publication — likely public domain but author death year unconfirmed.`
    : `Author died ${deathYear}. UK copyright expires ${pdYear}.`;

  const alreadyDigitised = n % 7 === 0; // ~14% chance
  const gutenbergId = alreadyDigitised ? 10000 + (n % 50000) : null;

  const preLlm = publishYear < 2022;

  const aiValue =
    isPd && !alreadyDigitised && preLlm
      ? n % 3 === 0
        ? 'premium'
        : 'high'
      : alreadyDigitised
      ? 'medium'
      : 'low';

  const score =
    (aiValue === 'premium' ? 40 : aiValue === 'high' ? 30 : aiValue === 'medium' ? 20 : 5) +
    (isPd ? 25 : isLikelyPd ? 20 : 0) +
    (!alreadyDigitised ? 20 : 0) +
    (preLlm ? 15 : 0);

  const triageAction =
    alreadyDigitised && isPd
      ? 'already_available'
      : (aiValue === 'premium' || aiValue === 'high') && (isPd || isLikelyPd)
      ? 'scan_and_sell_data'
      : (aiValue === 'premium' || aiValue === 'high') && !isPd
      ? 'preserve_only'
      : 'sell_physical';

  const valueFactors: string[] = [];
  if (preLlm) valueFactors.push('pre-LLM era (pre-2022)');
  if (isPd || isLikelyPd) valueFactors.push('public domain — no licensing needed');
  else valueFactors.push('copyrighted — requires licensing');
  if (!alreadyDigitised) valueFactors.push('not on Gutenberg — potentially unique data');
  else valueFactors.push('already on Gutenberg — lower uniqueness value');
  if (keywords.length) valueFactors.push(`niche domain: ${keywords.slice(0, 2).join(', ')}`);

  const resalePlatform =
    aiValue === 'premium'
      ? 'abebooks'
      : aiValue === 'high'
      ? 'abebooks'
      : aiValue === 'medium'
      ? 'ebay'
      : 'amazon_or_ziffit';

  const resaleReason =
    aiValue === 'premium'
      ? 'Rare PD book — scan for data then resell on AbeBooks for collector market.'
      : aiValue === 'high'
      ? 'Valuable book — AbeBooks for broader antiquarian reach.'
      : 'Moderate value — eBay for faster turnover.';

  return {
    isbn: seed.length >= 10 ? seed : null,
    title,
    subtitle: null,
    author_name: author.name,
    author_birth_year: author.birth,
    author_death_year: deathYear,
    publisher,
    publish_year: publishYear,
    language: 'en',
    page_count: 200 + (n % 600),
    subject_keywords: [...keywords],
    description: `A scholarly work on ${keywords[0] ?? 'the subject'} from the ${publishYear < 1920 ? 'Victorian' : 'Edwardian'} era, representing important historical scientific knowledge.`,
    public_domain_status: pdStatus,
    public_domain_reason: pdReason,
    ai_training_value: aiValue,
    ai_value_factors: valueFactors,
    pre_llm_era: preLlm,
    triage_action: triageAction,
    triage_score: Math.min(score, 100),
    triage_notes: null,
    already_digitised: alreadyDigitised,
    gutenberg_id: gutenbergId,
    gutenberg_url: gutenbergId ? `https://www.gutenberg.org/ebooks/${gutenbergId}` : null,
    openlibrary_id: null,
    openlibrary_url: null,
    resale_recommendation: {
      platform: resalePlatform,
      platform_label: resalePlatform === 'abebooks' ? 'AbeBooks' : resalePlatform === 'ebay' ? 'eBay' : 'Amazon / Ziffit',
      reason: resaleReason,
      estimated_price_range: aiValue === 'premium' ? '£15–£50' : aiValue === 'high' ? '£8–£20' : '£3–£10',
      listing_tips: [
        'Include photographs of title page, spine, and any illustrations.',
        'Note edition, binding condition, and any annotations or bookplates.',
      ],
    },
    cached: false,
    triage_run_at: new Date().toISOString(),
    warnings: [],
  };
}
